import type { LauncherHomeResponse } from './types'

export const bootstrapHome: LauncherHomeResponse = {
  modules: [
    {
      module_id: 'home',
      label: 'Home',
      description: 'Workspace principal del launcher.',
      icon: 'home',
      aliases: ['inicio'],
      flow_prefixes: [],
      menus: [],
      flow_count: 0,
    },
    {
      module_id: 'loan',
      label: 'Prestamos',
      description: 'Origina, paga, desembolsa y refinancia prestamos.',
      icon: 'badge-dollar-sign',
      aliases: ['loan', 'prestamo'],
      flow_prefixes: ['loan'],
      menus: [
        { id: 'loan-create', label: 'Crear prestamo', path: '/apps/loan/create' },
        { id: 'loan-payment', label: 'Pago de prestamo', path: '/apps/loan/payment' },
        { id: 'loan-refinance', label: 'Refinanciamiento', path: '/apps/loan/refinance' },
      ],
      flow_count: 4,
    },
    {
      module_id: 'customer',
      label: 'Clientes',
      description: 'Alta, consulta y mantenimiento de clientes.',
      icon: 'users',
      aliases: ['cliente', 'customer'],
      flow_prefixes: ['customer'],
      menus: [{ id: 'customer-create', label: 'Crear cliente', path: '/apps/customer/create' }],
      flow_count: 1,
    },
    {
      module_id: 'workflow',
      label: 'Workflow',
      description: 'Ejecuciones, aprobaciones y trazas.',
      icon: 'workflow',
      aliases: ['flujo'],
      flow_prefixes: [],
      menus: [],
      flow_count: 0,
    },
    {
      module_id: 'admin',
      label: 'Admin',
      description: 'Registro, permisos y configuracion.',
      icon: 'settings',
      aliases: ['administracion'],
      flow_prefixes: [],
      menus: [],
      flow_count: 0,
    },
  ],
  featured_flows: [
    {
      module_id: 'loan',
      flow_id: 'flow.loan.create',
      flow_name: 'Crear prestamo',
      intent: 'Crear una nueva solicitud de prestamo.',
      business_event: 'loan.create.requested',
      source_path: 'config/definitions/flows/loan_create.flow.yaml',
      source_type: 'yaml',
      plan_steps: 4,
      user_tasks: ['capturar_cliente', 'validar_producto', 'confirmar_condiciones'],
      related_process_ids: ['process.loan.create'],
      confidence: 0.92,
      explanation: 'Flujo para originacion inicial de prestamo.',
    },
    {
      module_id: 'loan',
      flow_id: 'flow.loan.payment',
      flow_name: 'Pago de prestamo',
      intent: 'Registrar o programar un pago de prestamo.',
      business_event: 'loan.payment.requested',
      source_path: 'config/definitions/flows/loan_payment.flow.yaml',
      source_type: 'yaml',
      plan_steps: 3,
      user_tasks: ['seleccionar_prestamo', 'capturar_pago', 'confirmar_pago'],
      related_process_ids: ['process.loan.payment'],
      confidence: 0.9,
      explanation: 'Flujo para pagos y abonos a prestamos.',
    },
    {
      module_id: 'customer',
      flow_id: 'flow.customer.create',
      flow_name: 'Crear cliente',
      intent: 'Crear un nuevo cliente en la plataforma.',
      business_event: 'customer.create.requested',
      source_path: 'config/definitions/flows/customer_create.flow.yaml',
      source_type: 'yaml',
      plan_steps: 3,
      user_tasks: ['capturar_identidad', 'validar_contacto', 'crear_cliente'],
      related_process_ids: ['process.customer.create'],
      confidence: 0.88,
      explanation: 'Flujo para alta de cliente.',
    },
  ],
  recent_flows: [],
  navigation: {},
}
