from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from app.knowledge_base.models import EnterpriseAsset


@dataclass(frozen=True)
class StagedAssetSet:
    asset_set_id: str
    asset_type: str
    version: str
    manifest_path: Path
    asset_count: int

    def to_dict(self) -> dict[str, Any]:
        return {
            "asset_set_id": self.asset_set_id,
            "asset_type": self.asset_type,
            "version": self.version,
            "manifest_path": str(self.manifest_path),
            "asset_count": self.asset_count,
        }


class IngestionAssetSetStager:
    """Write canonical ingestion assets as governed AssetSet YAML proposals."""

    def __init__(self, staging_root: Path):
        self.staging_root = staging_root

    def write_run(
        self,
        *,
        run_id: str,
        assets: list[EnterpriseAsset],
        version: str = "1.0.0",
    ) -> list[StagedAssetSet]:
        run_root = self.staging_root / run_id
        grouped: dict[str, list[EnterpriseAsset]] = {}
        for asset in assets:
            grouped.setdefault(asset.asset_type, []).append(asset)

        staged: list[StagedAssetSet] = []
        for asset_type, group in sorted(grouped.items()):
            asset_set_id = f"ingest-{run_id}-{asset_type}-set"
            asset_set_root = run_root / f"{asset_type}-set"
            assets_root = asset_set_root / "assets"
            assets_root.mkdir(parents=True, exist_ok=True)
            entries: list[str] = []
            seen_asset_ids: set[str] = set()
            for asset in sorted(group, key=lambda item: item.asset_id):
                if asset.asset_id in seen_asset_ids:
                    continue
                seen_asset_ids.add(asset.asset_id)
                document = self._asset_document(asset, version=version)
                filename = self._asset_filename(asset.asset_id)
                asset_path = assets_root / filename
                asset_path.write_text(
                    yaml.safe_dump(document, sort_keys=False, allow_unicode=True),
                    encoding="utf-8",
                )
                entries.append(f"assets/{filename}")

            first = group[0]
            manifest = {
                "apiVersion": "catalog.unify/v1",
                "kind": "AssetSet",
                "metadata": {
                    "id": asset_set_id,
                    "name": f"Ingestion {asset_type} candidates",
                    "version": version,
                    "domain": self._payload_value(first, "domain_id"),
                    "module": self._payload_value(first, "module_id"),
                    "description": f"Generated by ingestion run {run_id}.",
                    "tags": ["ingestion", asset_type],
                },
                "spec": {
                    "assetType": asset_type,
                    "assets": entries,
                },
            }
            manifest_path = asset_set_root / "asset-set.yaml"
            manifest_path.write_text(
                yaml.safe_dump(manifest, sort_keys=False, allow_unicode=True),
                encoding="utf-8",
            )
            staged.append(
                StagedAssetSet(
                    asset_set_id=asset_set_id,
                    asset_type=asset_type,
                    version=version,
                    manifest_path=manifest_path,
                    asset_count=len(entries),
                )
            )
        return staged

    @staticmethod
    def _asset_document(asset: EnterpriseAsset, *, version: str) -> dict[str, Any]:
        payload = dict(asset.payload)
        if asset.asset_type == "asset_set":
            if not payload.get("primary_asset_type"):
                payload["primary_asset_type"] = next(
                    (relation.metadata.get("asset_type") for relation in asset.relations if relation.metadata.get("asset_type")),
                    "asset",
                )
            if not payload.get("members"):
                asset_ids = list(payload.get("asset_ids") or [])
                payload["members"] = [{"asset_id": asset_id} for asset_id in asset_ids]
        return {
            "asset_id": asset.asset_id,
            "asset_type": asset.asset_type,
            "name": asset.name or asset.asset_id,
            "version": version,
            "owner": asset.owner,
            "description": asset.description,
            "text": asset.text,
            "tags": asset.tags,
            "relations": [relation.model_dump(mode="json") for relation in asset.relations],
            "payload": payload,
        }

    @staticmethod
    def _payload_value(asset: EnterpriseAsset, key: str) -> str | None:
        value = asset.payload.get(key)
        return str(value) if value else None

    @staticmethod
    def _asset_filename(asset_id: str) -> str:
        safe = "".join(char if char.isalnum() or char in {"-", "_"} else "-" for char in asset_id)
        # Truncate to filesystem-safe length (200 chars max, leaving room for .yaml)
        if len(safe) > 200:
            safe = safe[:200]
        return f"{safe}.yaml"
