loan:
- prestamo
- credito
- credit
- financiamiento
loan_refinance:
- refinanciar
- refinanciacion
- bajar cuota
- renegociar credito
loan_conditions:
- cuota
- condiciones
- tasa
- plazo
payment:
- pago
- pagar
- abono
transfer:
- transferencia
- transferir
- cbu
- envio dinero
savings_account:
- cuenta
- cuenta ahorro
- ahorro
- account
claim:
- reclamo
- queja
- disputa
credit_note:
- nota credito
- nota de credito
debit_note:
- nota debito
- nota de debito
customer:
- cliente
- titular
- usuario

